version: '3.9'

services:
  mongodb:
    container_name: event-planner-mongo
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - /c/work/shadowing/volumes/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin