version: '3.9'

services:
  mongodb:
    container_name: event-planner-mongo
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - /c/work/shadowing/volumes/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  backend:
    container_name: event-planner-backend
    build: ./backend
    restart: always
    ports:
      - 8801:8801
    volumes:
      - /c/health-study/volumes/backend/logs:/app/logs
    environment:
      CONNECTION_STRING: mongodb://admin:admin@mongodb:27017/
      SECRET: HealthStudy
      LOG_FOLDER: ./logs/health-study.log
      LOG_LEVEL: DEBUG